import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto, Roboto_Serif } from "next/font/google";
import RecoidContextProvider from "./state-management/recoilContextProvider";

const roboto_Serif = Roboto_Serif({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto-serif",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto.variable} ${roboto_Serif.className}`}
    >
      <body className={inter.className}>
        <RecoidContextProvider>{children}</RecoidContextProvider>
      </body>
    </html>
  );
}
